### ISSUE TITLE
Needs some styling

### ISSUE THREAD

**Issue by tamburra** [Burry/Organizr-Plex-Theme#14]
Noticed some styling issues.  One being on the settings tab editor window and the other be in the plugin popup window.  Screenshots are self evident of locations.

**Screenshots**

<img width="1254" alt="screen shot 2018-12-08 at 6 09 07 pm" src="https://user-images.githubusercontent.com/16267805/49691774-922c5a80-fb17-11e8-94c0-aacd11e92f60.png">
<img width="1259" alt="screen shot 2018-12-08 at 6 08 23 pm" src="https://user-images.githubusercontent.com/16267805/49691775-922c5a80-fb17-11e8-95bd-97c6f4b171f9.png">

**User Info (please complete the following information):**
 - OS: OSX Mojave
 - Browser: Chrome
 - Version: latest

**Comment by jigahertz** [comment]
I recently noticed those as well. I went ahead and fixed them. Attempting to push my commits now

**Comment by Zachar2** [comment]
Any progress on this? I noticed more issues:

![1](https://user-images.githubusercontent.com/38113357/55746213-78edd900-5a39-11e9-9a98-c44b50bca175.png)

![3](https://user-images.githubusercontent.com/38113357/55746226-8014e700-5a39-11e9-9a50-d62046409d90.png)

**Comment by Zachar2** [comment]
Any progress on this? I noticed more issues:

![1](https://user-images.githubusercontent.com/38113357/55746506-1e08b180-5a3a-11e9-9c13-1f64873d4153.png)

![3](https://user-images.githubusercontent.com/38113357/55746520-2660ec80-5a3a-11e9-9cf4-8a98cd7f0e6f.png)

Thanks in advance.

**Comment by Burry** [comment]
Hey guys sorry for the total absence on this—been really busy with school and other work. Planning on releasing a major update sometime soon to accommodate all the new changes to v2 and to fix these lingering bugs, but it's just been on my backburner for now.

**Comment by Burry** [comment]
All these are fixed in [Version 3!](https://github.com/causefx/Organizr/pull/1198)
