### ISSUE TITLE
Sidebar is transparent on mobile

### ISSUE THREAD

**Issue by yannouchou** [Burry/Organizr-Plex-Theme#18]
**Describe the bug**
The sidebar appears too clear on mobile (tested with both Firefox and Safari on iOS), which makes it illegible. See screenshots.
I have found it hard to debug sine this doesn't affect my Desktop Firefox when using the "Responsive Design Mode" in the FF developer tools...

**Screenshots**
Firefox iOS:
![FF_iOS](https://user-images.githubusercontent.com/1210752/56338697-4bd9bd00-61d5-11e9-83b1-52c4b32b045e.PNG)

Safari iOS:
![Safari_iOS](https://user-images.githubusercontent.com/1210752/56338703-4ed4ad80-61d5-11e9-91ad-9b38ba5d7a6e.PNG)

Firefox desktop in responsive mode:
<img width="721" alt="FF_devtools" src="https://user-images.githubusercontent.com/1210752/56338706-51cf9e00-61d5-11e9-8b76-d1cd20bfea0f.png">

**User Info (please complete the following information):**
 - OS: iOS
 - Browser: Safari + Firefox
 - Version: Latest

**Comment by jockebq** [comment]
Having the same issue! Is there any fix?

**Comment by yannouchou** [comment]
I haven't tried myself yet but I might look into it.

**Comment by yannouchou** [comment]
I had a look with the Safari remote debugger. I don't fully understand what's going on but basically:
```
.sidebar, .sidebar-head, .user-bg, div[id^=request]:not(#request-input-div) .dropdown-toggle {
    -webkit-backdrop-filter: blur(30px);
    backdrop-filter: blur(30px)
}
```
* This section is properly showing up as the computed style of the `.sidebar` (`backdrop-filter` is not supported but `-webkit-backdrop-filter` is applied).
* However Safari behaves exactly as if this rule did not exist. Deactivating it in the inspector doesn't change the display.
* But inexplicably, **reapplying the rule** in the inspector causes the blurred background image to properly show up

So it looks more like a Safari bug than a CSS bug...

That being said, it doesn't mean there aren't any fixes, but right now they're a bit beyond my skills.
I suspect there might be a way to activate the fallback to the section under `@supports not (backdrop-filter: blur(30px))` to apply the fallback style that uses a background image instead of `blur()`...

**Comment by yannouchou** [comment]
Anyway until we can find a real fix, for now my workaround is to define in Organizr's "Custom CSS" section the following:
```
@media screen and (max-width:767px) {
    .sidebar {
        background: url(https://raw.githubusercontent.com/Burry/organizr-v2-plex-theme/master/images/background/noise.png) center center fixed, url(https://raw.githubusercontent.com/Burry/organizr-v2-plex-theme/master/images/background/blur-light.png) center center / cover no-repeat fixed !important
    }
}
```

**Comment by Burry** [comment]
@yannouchou Thanks for investigating. Seems like it's an experimental feature that needs some love from the WebKit and Blink teams, but it works well enough on desktop Safari. Released a temporary fix in [Version 3](https://github.com/causefx/Organizr/pull/1198) that uses the fallback style with no transparency on mobile.

**Comment by yannouchou** [comment]
Thanks @Burry 
I kind of suspect that the `blur` works but is computed _before_ the sidebar slides open, hence when it's over nothingness... which would explain why toggling the rule off/on while the sidebar is opened would fix the issue. But that's just speculation. Anyway, thanks for the fix, I think it's a very reasonable workaround!

**Comment by yannouchou** [comment]
Any idea how to make Organizr see and install the latest version?

**Comment by Burry** [comment]
@causefx will need to approve the PR, but if you want to manually update, you can replace the old Plex.css in Organizr's `Dashboard/css/themes/` with the [new one](https://raw.githubusercontent.com/Burry/Organizr-Plex-Theme/master/css/Plex.css).

**Comment by causefx** [comment]
Merged!  :)

**Comment by yannouchou** [comment]
Hmmm, doesn't seem to fix it for me...
Actually, I even lost the background grain effect from the main page:
![IMG_1021](https://user-images.githubusercontent.com/1210752/59590070-72ed3600-9115-11e9-98b0-a53976795c8c.PNG)


@Burry having a quick look at your fix, didn't you mean `@media screen and (max-width: 768px)` instead of `@media screen and (min-width: 768px)` ?

**Comment by Burry** [comment]
🤦‍♂️ Yep it should be max-width instead, will fix when I get home. Though it looks like your phone is still loading the old stylesheet: it was pretty “sticky” for me too even after clearing site data so was hard to test, but here’s what it currently looks like on iOS 13:

![Screen shot](https://i.imgur.com/2ibbr7O.jpg)
