### ISSUE TITLE
Looks like something changed

### ISSUE THREAD

**Issue by pieman16** [Burry/Organizr-Plex-Theme#20]
Looks like you changed the background. 
https://raw.githubusercontent.com/Burry/organizr-v2-plex-theme/master/images/background/blur-light.png

**Comment by Burry** [comment]
I did now, there's a new background in [Version 3](https://github.com/causefx/Organizr/pull/1198) to bring the theme more in-line with the new web client on [app.plex.tv](https://app.plex.tv/desktop).
