### ISSUE TITLE
Horizontal bar not working correctly?

### ISSUE THREAD

**Issue by jockebq** [Burry/Organizr-Plex-Theme#21]
**Describe the bug**
If you use horizontal bar, the icons and text looks weird (cut off) and the spacing from the top bar is off.

**To Reproduce**
If not self-evident, please provide steps to reproduce the behavior:
1. Go to 'Settings->Themes'
2. Click on 'Horizontal'
3. Observe style error

**Screenshots**
![plex](https://user-images.githubusercontent.com/40036309/59490238-6c945b00-8e84-11e9-9f12-45793d6d4aa3.png)

**User Info (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by Burry** [comment]
Sorry, the theme currently depends on base styles defined by the dark style, and it won't work with the horizontal style.
